service: get-products-list-API

frameworkVersion: '3'

useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ${env:REGION}
  environment:
    REGION:  ${env:REGION}
    PRODUCTS_TABLE: ${env:PRODUCTS_TABLE}
    STOCK_TABLE: ${env:STOCK_TABLE}


functions:
  getProductsList:
    handler: getProductsList/getProductsList.getProductsList
    role: ${env:DB_ACCESS_ROLE}
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductsById:
    handler: getProductsById/getProductsById.getProductsById
    role: ${env:DB_ACCESS_ROLE}
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true

  createProduct:
    handler: createProduct/createProduct.createProduct
    role: ${env:DB_ACCESS_ROLE}
    events:
      - http:
          path: products
          method: post
          cors: true

